# -*- coding: utf-8 -*-
"""Text to Image generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1srFpl9sFUiuBf-MZSjjd1PxrIQgXTHVT
"""

# Installing all required packages from requirements.txt
!pip install -r requirements.txt

# Importing StableDiffusionPipeline to use pre-trained Stable Diffusion models
from diffusers import StableDiffusionXLPipeline
# Image is a class for the PIL module to visualize images in a Python Notebook
from PIL import Image
# Importing PyTorch library, for building and training neural networks
import torch

# Loading SDXL 1.0 model
model_id = "stabilityai/stable-diffusion-xl-base-1.0"
device = "cuda" if torch.cuda.is_available() else "cpu"

# Creating the pipeline and moving pipeline to the appropriate device
pipeline = StableDiffusionXLPipeline.from_pretrained(model_id,
    torch_dtype=torch.float16 if device == "cuda" else torch.float32,
    use_safetensors=True).to(device)

# Defining function for the creation of a grid of images
def image_grid(imgs, rows, cols):
    assert len(imgs) == rows*cols
    w, h = imgs[0].size
    grid = Image.new('RGB', size = (cols*w,rows * w))
    grid_w, grid_h = grid.size
    for i, img in enumerate(imgs):
        grid.paste(img, box = ((i%cols)*w, (i // cols)*h))
    return grid

print("Welcome to Text-To-Image generator...")
flag=1
while(flag==1):
  print("Enter the prompt to generate the images:")
  prompt=input()
  print("Enter the number of images to be generated:")
  n_images=int(input())
  prompt=[prompt]*n_images
  images = pipeline(prompt=prompt,
    negative_prompt=["blurry, low quality, deformed, distorted, out of frame"] * n_images,
    num_inference_steps=50,
    guidance_scale=10.0,).images
  c = int(n_images**0.5)
  r = (n_images + c- 1)//c
  grid = image_grid(images,rows=r,cols=c)
  print("Here is your output:")
  display(grid)
  print("If you want to continue, PRESS 1\n If you want to exit, PRESS 0")
  while True: # Handling invalid input
    try:
      flag=int(input())
      break  # Exit the loop if input is valid
    except ValueError:
      print("Invalid input. Please enter 1 or 0.")
print("Thank you !!!")